config/routes.rb
InOutBoard::Application.routes.draw do
  devise_for :employees
  resources :status_selects

  resources :employees

  resources :statuses

  resources :offices
  
  get '/directories', to: 'office_directories#index'
  
  root to: 'office_directories#index'
  

end

app/models/office.rb
class Office < ActiveRecord::Base
  
  has_many :employees, -> { order "first_name ASC" }, :foreign_key => 'default_office_id'
  
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @offices = Office.all
  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to @office, notice: 'Office was successfully created.' }
        format.json { render action: 'show', status: :created, location: @office }
      else
        format.html { render action: 'new' }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to @office, notice: 'Office was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:office_name, :geoinfo, :geofence)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for @office, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :office_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :office_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :geoinfo, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :geoinfo, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :geofence, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :geofence, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                offices_path, :class => 'btn' %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<%- model_class = Office -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/offices/index.html.erb
<%- model_class = Office -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= model_class.human_attribute_name(:office_name) %></th>
      <th><%= model_class.human_attribute_name(:geoinfo) %></th>
      <th><%= model_class.human_attribute_name(:geofence) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @offices.each do |office| %>
      <tr>
        <td><%= link_to office_path(office) do %>
			<i class="bgsmcircle fa fa-arrow-right"></i>
			<% end %>
		</td>
        <td><%= office.office_name %></td>
        <td><%= office.geoinfo %></td>
        <td><%= office.geofence %></td>
        <td><%=l office.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_office_path(office), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      office_path(office),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_office_path,
            :class => 'btn btn-primary' %>

app/views/offices/new.html.erb
<%- model_class = Office -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/offices/show.html.erb
<%- model_class = Office -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:office_name) %>:</strong></dt>
  <dd><%= @office.office_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:geoinfo) %>:</strong></dt>
  <dd><%= @office.geoinfo %></dd>
  <dt><strong><%= model_class.human_attribute_name(:geofence) %>:</strong></dt>
  <dd><%= @office.geofence %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              offices_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_office_path(@office), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              office_path(@office),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>