config/routes.rb
InOutBoard::Application.routes.draw do
  devise_for :employees
  resources :status_selects

  resources :employees

  resources :statuses

  resources :offices
  
  get '/directories', to: 'office_directories#index'
  
  root to: 'office_directories#index'
  

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render action: 'show', status: :created, location: @status }
      else
        format.html { render action: 'new' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:in_out, :on_off, :status_select_id, :current_location, :return, :employee_id)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_for @status, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :in_out, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :in_out, :class => 'text_field', :value => false %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :on_off, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :on_off, :class => 'text_field', :value => false %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :status_select_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :status_select_id, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :current_location, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :current_location, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :return, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :return, :class => 'text_field', :value => 1.day.from_now %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :employee_id, :class => 'control-label' %>
    <div class="controls">
      <%= f.collection_select :employee_id, Employee.all, :id, :full_name, :class => 'collection_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                statuses_path, :class => 'btn' %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statuses/index.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th></th>
      <th><%= model_class.human_attribute_name(:in_out) %></th>
      <th><%= model_class.human_attribute_name(:on_off) %></th>
      <th><%= model_class.human_attribute_name(:status_select_id) %></th>
      <th><%= model_class.human_attribute_name(:current_location) %></th>
      <th><%= model_class.human_attribute_name(:return) %></th>
      <th><%= model_class.human_attribute_name(:employee_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= link_to status_path(status) do %>
  			<i class="bgsmcircle fa fa-arrow-right"></i>
  			<% end %>
  		</td>
        <td><%= status.in_out %></td>
        <td><%= status.on_off %></td>
        <td><%= status.status_select_id %></td>
        <td><%= status.current_location %></td>
        <td><%= status.return %></td>
        <td><%= status.employee.first_name %></td>
        <td><%=l status.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_status_path(status), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      status_path(status),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_status_path,
            :class => 'btn btn-primary' %>

app/views/statuses/new.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/statuses/show.html.erb
<%- model_class = Status -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:in_out) %>:</strong></dt>
  <dd><%= @status.in_out %></dd>
  <dt><strong><%= model_class.human_attribute_name(:on_off) %>:</strong></dt>
  <dd><%= @status.on_off %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status_select_id) %>:</strong></dt>
  <dd><%= @status.status_select_id %></dd>
  <dt><strong><%= model_class.human_attribute_name(:current_location) %>:</strong></dt>
  <dd><%= @status.current_location %></dd>
  <dt><strong><%= model_class.human_attribute_name(:return) %>:</strong></dt>
  <dd><%= @status.return %></dd>
  <dt><strong><%= model_class.human_attribute_name(:employee_id) %>:</strong></dt>
  <dd><%= @status.employee_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              statuses_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_status_path(@status), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              status_path(@status),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>