config/routes.rb
InOutBoard::Application.routes.draw do
  devise_for :employees
  resources :status_selects

  resources :employees

  resources :statuses

  resources :offices
  
  get '/directories', to: 'office_directories#index'
  
  root to: 'office_directories#index'
  

end

app/views/layouts/_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/_signedinas.html.erb
<% if current_employee %>
  Logged in as:<br/><strong><%= current_employee.email %></strong>
  <br/>|
  <%= link_to "Edit", edit_employee_registration_path, :class => 'navbar-link'%> |
  <%= link_to "Invite", new_employee_invitation_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_employee_session_path, method: :delete, :class => 'navbar-link'  %> |
  <br/><br/>
  <%= mail_to "warmbowski+tkqdp06d5gddiem0mdfv@boards.trello.com", "Email support", subject: "Starboard support submission", :class => 'navbar-link' %>
<% else %>
  <%= link_to "Request Invitation", accept_employee_invitation_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_employee_session_path, :class => 'navbar-link'  %> |
<% end %>
<br/><br/>
<h3 class="list" style="background-color: #C0150C; color: white; text-align: center; border: 1px solid black;"><%= Date.today.to_s(:short).upcase %></h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Status Board</title>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <script type="text/javascript">
      window.currentUser = {
          id : "<%= current_employee.id if current_employee %>"
      }
  </script>
</head>
<body>
   <span id="forkongithub"><a href="https://github.com/warmbowski/in_out_board">Fork me on GitHub</a></span>	<nav class="navbar navbar-default" role="navigation">
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <!-- <a class="navbar-brand" href="#">Brand</a> -->
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
			 <li><a href="/">Home</a></li>
	        <!-- <li><a href="offices">Offices</a></li>
	        <li><a href="employees">Employees</a></li> -->
	        <!-- <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	            <li class="divider"></li>
	            <li><a href="#">One more separated link</a></li>
	          </ul>
	        </li> -->
	      </ul>
	      <form class="navbar-form navbar-left" role="search">
	        <div class="form-group">
	          <input type="text" class="form-control" placeholder="Search">
	        </div>
	        <button type="submit" class="btn btn-default">Submit</button>
	      </form>
	      <!-- <ul class="nav navbar-nav navbar-right">
	        <li><a href="#">Link</a></li>
	        <li class="dropdown">
	          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
	          <ul class="dropdown-menu">
	            <li><a href="#">Action</a></li>
	            <li><a href="#">Another action</a></li>
	            <li><a href="#">Something else here</a></li>
	            <li class="divider"></li>
	            <li><a href="#">Separated link</a></li>
	          </ul>
	        </li>
	      </ul> -->
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
<div class="container">
	<div class="row">
		<%= render :partial => "layouts/messages", :locals => {:flash => flash} %>
		<div class="span10"><%= yield %></div>
		<div class="span2"  align="right">
			<br/>
			<br/>
			<br/>
			<br/>
			<h1><i class="bglogocircle fa fa-rocket" align="center"></i> Star Board</h1>
			<br/>
			<%= render :partial => "layouts/signedinas" %>
		</div>
	</div>
</div>
</body>
</html>